name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Upravte podle názvu vaší hlavní větve (main nebo master)
  workflow_dispatch:    # Umožní manuální spuštění workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'
          cache: 'npm'

      - name: Install dependencies 📦
        run: npm ci

      - name: Build 🔧
        run: npm run build -- --configuration production --base-href=/Portfolio/

      - name: Create 404.html 🔄
        run: cp dist/portfolio/browser/index.html dist/portfolio/browser/404.html
        # Upravte "romiiis-portfolio" na skutečný název vaší aplikace - najdete ho ve složce dist po buildu

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/portfolio/browser
          # Upravte "romiiis-portfolio" na skutečný název vaší aplikace - najdete ho ve složce dist po buildu
